import { useState } from 'react';
import { ArrowUpRight, Check, ChevronDown, LockKeyhole, Menu, X } from 'lucide-react';
import './index.css';

type FormData = { fullName: string; email: string; whatsapp: string; profession: string; city: string; participantType: string; socialLink: string; consent: boolean };
type Flow = 'landing' | 'register' | 'payment' | 'success';
const initialForm: FormData = { fullName: '', email: '', whatsapp: '', profession: '', city: '', participantType: '', socialLink: '', consent: false };
const days = [
  ['01', 'Introduction to AI & Generative Design', 'The landscape, language and ethics of a new design medium.'],
  ['02', 'Generative AI Tools & Workflows', 'Build a practical toolkit for exploration and production.'],
  ['03', 'Prompt Engineering for Designers', 'Turn instinct into repeatable, articulate direction.'],
  ['04', 'LLM Basics & Power of Language Models', 'Understand the engine behind the interface.'],
  ['05', 'Research in LLM: Techniques & Applications', 'Read, question, synthesize and make meaning faster.'],
  ['06', 'Hands-on Project Development', 'Move from a brief to a considered, working outcome.'],
  ['07', 'Project Presentation & Feedback', 'Share the work, receive critique, leave with momentum.']
];
const learnings = ['Generative AI tools for ideation & visualization', 'AI workflows for architectural & interior design', 'Prompt engineering for design & research', 'LLM fundamentals & practical applications', 'AI for research, content analysis & synthesis'];
const audience = ['Architects', 'Interior designers', 'Design students', 'Researchers & professionals', 'The AI-curious'];

function Logo() { return <div className="logo" aria-label="Company logo placeholder"><span className="logo-mark">/</span><span>YOUR<br />LOGO</span></div>; }
function Price({ dark = false }: { dark?: boolean }) { return <span className={dark ? 'price price-dark' : 'price'}>₹1,499<span>/-</span></span>; }
function App() {
  const [flow, setFlow] = useState<Flow>('landing'); const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({}); const [menu, setMenu] = useState(false);
  const goRegister = () => { setFlow('register'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const update = (key: keyof FormData, value: string | boolean) => { setForm(f => ({ ...f, [key]: value })); setErrors(e => ({ ...e, [key]: '' })); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const required: (keyof FormData)[] = ['fullName', 'email', 'whatsapp', 'profession', 'city', 'participantType']; const next: typeof errors = {}; required.forEach(key => { if (!form[key]) next[key] = 'Required'; }); if (!form.consent) next.consent = 'Please accept to continue'; setErrors(next); if (!Object.keys(next).length) setFlow('payment'); };
  if (flow === 'register' || flow === 'payment' || flow === 'success') return <FlowPage flow={flow} form={form} onChange={update} errors={errors} onSubmit={submit} onBack={() => setFlow('landing')} onPay={() => setFlow('success')} />;
  return <Landing onEnroll={goRegister} menu={menu} setMenu={setMenu} />;
}
function Header({ onEnroll, menu, setMenu }: { onEnroll: () => void; menu: boolean; setMenu: (v: boolean) => void }) { return <header className="site-header"><a href="#top" className="brand-link"><Logo /></a><nav className={menu ? 'nav open' : 'nav'}><a href="#learn">The curriculum</a><a href="#days">7 days</a><a href="#who">Who it is for</a><button className="nav-cta" onClick={onEnroll}>Enroll <ArrowUpRight size={15} /></button></nav><button className="menu-button" aria-label="Toggle navigation" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></header>; }
function Landing({ onEnroll, menu, setMenu }: { onEnroll: () => void; menu: boolean; setMenu: (v: boolean) => void }) { return <div id="top"><Header onEnroll={onEnroll} menu={menu} setMenu={setMenu} /><main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">One week intensive <span /> Online workshop</p><h1>Design in<br /><em>Generative AI</em><br /><span>& research in LLM</span></h1><p className="hero-sub">Design smarter. Research deeper.<br />Create impact.</p><div className="hero-actions"><button className="button button-gold" onClick={onEnroll}>Enroll now <Price /></button><a className="text-link" href="#days">View workshop <ArrowUpRight size={17} /></a></div></div><div className="hero-art"><div className="art-label">A new literacy<br /><strong>for the<br />design field</strong></div><div className="art-note">01 / 07</div></div><div className="hero-meta"><span>01</span><span>Design education for a changing practice</span><span>Scroll to explore ↓</span></div></section>
  <section className="intro section-pad"><div className="section-kicker">/ The proposition</div><div className="intro-grid"><h2>Where thoughtful<br /><span>design meets</span><br />machine intelligence.</h2><div className="intro-copy"><p>AI is not replacing the designer. It is expanding the designer's field of vision.</p><p>This seven-day intensive is a working introduction to the tools, methods and questions shaping the next chapter of creative practice.</p><a className="text-link dark-link" href="#learn">Read the curriculum <ArrowUpRight size={17} /></a></div></div></section>
  <section className="statement"><div className="statement-inner"><span className="section-kicker">/ A working week</span><p>Less <i>prompting.</i><br />More <strong>thinking.</strong></p><span className="statement-side">01 — 07<br />A compact, rigorous<br />studio of ideas.</span></div></section>
  <section className="section-pad" id="who"><div className="section-kicker">/ Who it is for</div><div className="split-heading"><h2>Come as you are.<br /><span>Leave with a new lens.</span></h2><p>Built for people who want to make AI useful, expressive and responsible in their own practice.</p></div><div className="audience-grid">{audience.map((item, i) => <div className="audience-item" key={item}><span>0{i + 1}</span><strong>{item}</strong><ArrowUpRight size={18} /></div>)}</div></section>
  <section className="learn section-pad" id="learn"><div className="section-kicker">/ What you will learn</div><div className="learn-grid"><h2>Five shifts<br /><span>in perspective.</span></h2><div>{learnings.map((item, i) => <div className="learning" key={item}><span>0{i + 1}</span><p>{item}</p><Check size={16} /></div>)}</div></div></section>
  <section className="days section-pad" id="days"><div className="section-kicker">/ The seven-day workshop</div><div className="days-head"><h2>One week.<br /><span>Real momentum.</span></h2><p>Each day builds on the last, moving from orientation to application, from curiosity to a project you can carry forward.</p></div><div className="day-list">{days.map(([number, title, copy]) => <details key={number} open={number === '01'}><summary><span className="day-num">{number}</span><strong>{title}</strong><ChevronDown size={18} /></summary><p>{copy}</p></details>)}</div></section>
  <section className="offer"><div className="offer-copy"><div className="section-kicker">/ Special offer</div><h2>Your next<br /><em>seven days</em><br />start here.</h2><p>One focused week to make the unfamiliar feel possible.</p></div><div className="offer-card"><span className="offer-tag">Limited seats · 100% online</span><small>JUST</small><Price dark /><div className="offer-rule" /><p>Includes all live sessions, project feedback, certificate of completion and community support.</p><button className="button button-navy" onClick={onEnroll}>Secure my seat <ArrowUpRight size={17} /></button></div></section>
  <section className="why section-pad"><div className="section-kicker">/ Why join</div><div className="why-grid"><h2>Make room<br /><span>for better questions.</span></h2><div className="benefits">{['Stay ahead with AI-powered design and research skills', 'Save time, increase creativity and productivity', 'Apply AI to real projects and research challenges', 'Learn from experts and connect with a like-minded community'].map((b, i) => <div key={b}><span>0{i + 1}</span><p>{b}</p></div>)}</div></div></section>
  <section className="final-cta"><p className="section-kicker">/ Begin the shift</p><h2>Transform the way you<br /><em>design & research</em> with AI.</h2><button className="button button-gold" onClick={onEnroll}>Enroll now <Price /></button></section>
 </main><footer><Logo /><p>Design education for a<br />more curious future.</p><div><a href="#top">Terms</a><a href="#top">Privacy</a><a href="#top">Refunds</a></div><small>© 2026 Your Company. Replace this with your company details.</small></footer><div className="mobile-cta"><button onClick={onEnroll}>Enroll now — ₹1,499/- <ArrowUpRight size={16} /></button></div></div>; }
function Field({ label, name, value, onChange, error, required = true, type = 'text' }: { label: string; name: keyof FormData; value: string; onChange: (k: keyof FormData, v: string) => void; error?: string; required?: boolean; type?: string }) { return <label className="field">{label}{required && <sup>*</sup>}<input type={type} value={value} onChange={e => onChange(name, e.target.value)} placeholder="Type here" />{error && <small>{error}</small>}</label>; }
function FlowPage({ flow, form, onChange, errors, onSubmit, onBack, onPay }: { flow: Flow; form: FormData; onChange: (k: keyof FormData, v: string | boolean) => void; errors: Partial<Record<keyof FormData, string>>; onSubmit: (e: React.FormEvent) => void; onBack: () => void; onPay: () => void }) { if (flow === 'success') return <div className="flow-shell"><Logo /><div className="success-box"><div className="success-icon"><Check /></div><p className="eyebrow">Payment successful</p><h1>You're officially<br /><em>registered.</em></h1><p>Your seat for the <strong>Design in Generative AI & Research in LLM</strong> 7-Day Intensive Workshop has been confirmed.</p><div className="receipt"><span>Participant name<strong>{form.fullName}</strong></span><span>Registration ID<strong>7D-{Math.floor(10000 + Math.random() * 89999)}</strong></span><span>Payment status<strong className="paid">PAID</strong></span></div><a className="button button-gold full" href="WHATSAPP_GROUP_LINK" onClick={e => e.preventDefault()}>Join WhatsApp workshop group <ArrowUpRight size={17} /></a><p className="fine-print">Please join the WhatsApp group to receive workshop schedule, meeting links, announcements and important updates.</p><button className="receipt-link">Download / view payment receipt</button></div></div>;
 if (flow === 'payment') return <div className="flow-shell"><Logo /><div className="payment-box"><button className="back" onClick={() => onBack()}>← Back to registration</button><p className="eyebrow">Secure checkout · Test mode</p><h1>Complete your<br /><em>enrollment.</em></h1><div className="pay-summary"><span>Seven-day intensive workshop</span><strong><Price /></strong></div><div className="secure-line"><LockKeyhole size={16} /> Razorpay secure hosted checkout · UPI · Cards · Net banking</div><button className="button button-navy full" onClick={onPay}>Continue to Razorpay <ArrowUpRight size={17} /></button><p className="fine-print">Payment verification happens on the server before your seat is marked paid. This demo button represents the Razorpay test checkout.</p></div></div>;
 return <div className="flow-shell"><Logo /><form className="registration-box" onSubmit={onSubmit}><button className="back" type="button" onClick={onBack}>← Back to workshop</button><p className="eyebrow">Reserve your place · 01 / 02</p><h1>Let's make<br /><em>something useful.</em></h1><p className="form-lead">Tell us a little about yourself. Your details are only used for workshop communication.</p><div className="form-grid"><Field label="Full name" name="fullName" value={form.fullName} onChange={onChange} error={errors.fullName} /><Field label="Email address" name="email" type="email" value={form.email} onChange={onChange} error={errors.email} /><Field label="WhatsApp number" name="whatsapp" value={form.whatsapp} onChange={onChange} error={errors.whatsapp} /><Field label="Profession" name="profession" value={form.profession} onChange={onChange} error={errors.profession} /><Field label="City" name="city" value={form.city} onChange={onChange} error={errors.city} /><label className="field">You are a<sup>*</sup><select value={form.participantType} onChange={e => onChange('participantType', e.target.value)}><option value="">Select one</option><option>Student</option><option>Professional</option></select>{errors.participantType && <small>{errors.participantType}</small>}</label><Field label="LinkedIn / Instagram" name="socialLink" value={form.socialLink} onChange={onChange} required={false} /></div><label className="consent"><input type="checkbox" checked={form.consent} onChange={e => onChange('consent', e.target.checked)} /><span>I agree to receive workshop-related communication on email and WhatsApp.</span></label>{errors.consent && <small className="consent-error">{errors.consent}</small>}<button className="button button-gold full" type="submit">Continue to payment <ArrowUpRight size={17} /></button><p className="fine-print">By continuing, you agree to our Terms, Privacy Policy and Refund / Cancellation Policy.</p></form></div>; }
export default App;
