import { ArrowUpLeft } from 'lucide-react';

const termsSections = [
  ['1. Workshop Information', 'The Workshop is an online educational program focused on Generative AI, AI-assisted design workflows, prompt engineering, Large Language Models (LLMs), and AI-based research applications. Workshop details, including dates, timings, curriculum, speakers, sessions, and other information, may be communicated through the website, email, WhatsApp, or other official communication channels.'],
  ['2. Registration', 'To register for the Workshop, participants may be required to provide accurate information, including full name, email address, WhatsApp/mobile number, profession, city, and student/professional status. You are responsible for ensuring that the information provided during registration is accurate and up to date. Registration is considered confirmed only after successful payment has been received and verified.'],
  ['3. Workshop Fee', 'The applicable Workshop fee is displayed on the registration/payment page. For the current Workshop, the displayed fee is ₹1,499/-. The fee may be subject to applicable taxes or payment-processing charges, where applicable. Payment is processed through the payment gateway made available on the website.'],
  ['4. Payment', 'By proceeding with payment, you authorize the applicable payment gateway to process the transaction. We do not collect or store your complete debit card, credit card, UPI PIN, banking password, or other sensitive payment credentials on our website. Payment information is processed by the applicable third-party payment service provider according to its own terms and privacy policies.'],
  ['5. Cancellation and Refund Policy', 'Workshop registrations are subject to the refund policy displayed on the registration/payment page. Unless otherwise expressly stated by the Workshop organizers, payments for confirmed registrations are non-refundable and non-transferable. If a refund is specifically approved by the organizers, the refund will be processed through the applicable payment gateway and may take additional time to reflect in the participant\'s account. In the event that the Workshop is cancelled by the organizers, participants will be informed about the applicable refund or alternative arrangements.'],
  ['6. Access to the Workshop', 'After successful payment verification, participants may receive access to the Workshop\'s official communication channels, including a WhatsApp group, email communications, meeting links, learning materials, or other resources. Workshop access is intended solely for the registered participant. Participants must not share paid Workshop access, meeting links, recordings, course material, or private communication-group links with individuals who have not registered.'],
  ['7. WhatsApp Group', 'The official WhatsApp group may be used for Workshop-related communication, announcements, schedules, resources, reminders, and support. Participants are expected to maintain respectful and professional conduct. The organizers reserve the right to remove participants from the group for spam, harassment, abusive behaviour, unauthorized promotion, disruption, or other inappropriate conduct.'],
  ['8. Intellectual Property', 'All Workshop materials, including presentations, documents, templates, prompts, videos, recordings, graphics, course material, written content, and other educational resources are protected by applicable intellectual-property laws and remain the property of their respective owners. Materials are provided for personal educational use and may not be reproduced, resold, redistributed, published, uploaded, commercially exploited, or shared without prior written permission.'],
  ['9. Recordings', 'Where sessions are recorded, the organizers may provide recordings to registered participants for educational purposes. Participants must not redistribute, publicly upload, sell, or commercially exploit Workshop recordings. Participants should avoid sharing confidential or sensitive information during recorded sessions.'],
  ['10. Educational Disclaimer', 'The Workshop is intended for educational and informational purposes. The tools, platforms, AI models, software, workflows, and techniques discussed may change over time. The organizers do not guarantee any particular AI result, business outcome, research outcome, professional opportunity, or financial outcome. Participants are responsible for independently evaluating AI-generated information.'],
  ['11. Third-Party Services', 'The Workshop may reference third-party AI tools, payment providers, communication platforms, video-conferencing services, and other software. Such services are governed by their own terms and policies. We are not responsible for changes, interruptions, outages, pricing changes, or policies of third-party services.'],
  ['12. Participant Conduct', 'Participants agree not to harass or threaten others, disrupt sessions, spam communication channels, share inappropriate or unlawful content, attempt unauthorized access, record or distribute content without permission, misuse materials, or impersonate another participant or organizer. Violations may result in removal without refund, where permitted by applicable law.'],
  ['13. Changes to the Workshop', 'The organizers may reasonably modify session timings, curriculum, speakers, workshop format, platforms used, session sequence, or learning resources. Significant changes will be communicated to registered participants.'],
  ['14. Limitation of Liability', 'To the extent permitted by applicable law, the organizers shall not be responsible for indirect, incidental, consequential, or other losses arising from participation or reliance on information provided. The organizers are also not responsible for technical problems caused by a participant\'s internet connection, device, software, or third-party platforms.'],
  ['15. Contact', 'For questions regarding registration, payment, Workshop access, or these Terms, please contact us using the official contact details provided on the website. Email: contact@reeghdesign.com. WhatsApp/Phone: 8530863658. Company/Organization: RéEGH.'],
  ['16. Acceptance', 'By registering for the Workshop and completing payment, you confirm that you have read and accepted these Terms & Conditions.'],
] as const;

const privacySections = [
  ['1. Information We Collect', 'When you register for the Workshop, we may collect your full name, email address, mobile/WhatsApp number, profession, city, student/professional status, social-media or professional profile if voluntarily provided, registration details, and payment and transaction information.'],
  ['2. Payment Information', 'Payments are processed through third-party payment providers. We do not intentionally collect or store complete credit/debit card numbers, CVV, UPI PIN, internet banking passwords, or other confidential banking credentials. We may receive payment status, transaction/reference ID, amount paid, date and time, payment method, and related transaction metadata.'],
  ['3. How We Use Your Information', 'We may use your information to process registrations, verify payments, confirm participation, send workshop-related emails and WhatsApp messages, share session links and schedules, provide resources, respond to support requests, manage participant records, issue certificates, prevent fraud, comply with legal obligations, and improve the website and Workshop experience.'],
  ['4. WhatsApp Communication', 'If you provide your WhatsApp/mobile number and consent to Workshop communication, we may send registration confirmations, payment confirmations, reminders, session links, announcements, and important updates. If you join the official group, other members may see information WhatsApp makes visible according to your privacy settings.'],
  ['5. Email Communication', 'We may use your email address for registration confirmation, payment information, schedules, learning resources, announcements, and support communication. You may contact us if you no longer wish to receive non-essential communications.'],
  ['6. Sharing of Information', 'We do not sell or rent personal information. We may share necessary information with trusted payment processors, hosting providers, database/service providers, email providers, WhatsApp or communication platforms, video-conferencing platforms, and certificate or document providers. We may also disclose information where required by law.'],
  ['7. Data Security', 'We take reasonable technical and organizational measures to protect personal information against unauthorized access, alteration, disclosure, or destruction. However, no internet-based service can guarantee absolute security.'],
  ['8. Data Retention', 'We retain personal information only as reasonably necessary for Workshop administration, registration records, payment reconciliation, certificate issuance, customer support, legal, accounting, tax, regulatory requirements, and dispute resolution. Information may later be deleted or anonymized.'],
  ['9. Cookies and Website Technologies', 'Our website may use cookies or similar technologies to keep the website functioning, understand usage, improve performance, remember preferences, and analyze traffic. You can control cookies through browser settings.'],
  ['10. Third-Party Websites and Services', 'Our website may contain links to third-party websites, AI platforms, social-media platforms, payment services, or other external services. We are not responsible for their privacy practices, security, content, or policies.'],
  ['11. Children\'s Privacy', 'The Workshop is not specifically directed toward children. We do not knowingly collect personal information from children in violation of applicable law.'],
  ['12. Your Rights', 'Subject to applicable law, you may request access, correction, deletion where legally permitted, withdrawal of consent for certain processing, or information about how your data is used.'],
  ['13. Changes to this Privacy Policy', 'We may update this Privacy Policy to reflect changes in services, technology, legal requirements, or business practices. The updated version will be posted with a revised Last Updated date.'],
  ['14. Contact Us', 'Company/Organization: RéEGH. Email: contact@reeghdesign.com. WhatsApp/Phone: 8530863658. Website: the official Workshop website.'],
] as const;

export function PolicyPage({ kind, onBack }: { kind: 'terms' | 'privacy'; onBack: () => void }) {
  const isTerms = kind === 'terms';
  const sections = isTerms ? termsSections : privacySections;
  return <div className="policy-shell"><div className="policy-top"><a href="/" className="policy-back" onClick={event => { event.preventDefault(); onBack(); }}><ArrowUpLeft size={16} /> Back to workshop</a><span className="eyebrow">RéEGH · Legal</span></div><article className="policy-content"><p className="section-kicker">/ Legal information</p><h1>{isTerms ? 'Terms & Conditions' : 'Privacy Policy'}</h1><p className="policy-date">Last Updated: 28 August 2026</p><p className="policy-intro">{isTerms ? 'These Terms govern your registration for and participation in the Design in Generative AI & Research in LLM – 7-Day Intensive Online Workshop.' : 'This Privacy Policy explains how RéEGH collects, uses, stores, and protects personal information when you visit our website, register, make a payment, or interact with our communication channels.'}</p>{sections.map(([heading, text]) => <section className="policy-section" key={heading}><h2>{heading}</h2><p>{text}</p></section>)}</article></div>;
}
